#!/usr/bin/env python3
"""
Generate a standardized NFR Code Review Markdown report from structured input.

Usage:
    python generate_report.py --input review-data.json --output report.md

Input JSON schema:
{
  "files_reviewed": ["src/foo.py", "src/bar.py"],
  "dimensions": {
    "Code Design": {"score": "pass|concern|block", "evidence": ["..."]},
    "Readability": {"score": "pass|concern|block", "evidence": ["..."]},
    "Reliability": {"score": "pass|concern|block", "evidence": ["..."]},
    "Performance": {"score": "pass|concern|block", "evidence": ["..."]}
  },
  "action_items": [
    {"priority": "Block", "item": "...", "location": "foo.py:42", "dimension": "Reliability"}
  ],
  "highlights": ["Clean error handling in bar.py"],
  "static_analysis": {"tools": ["Pylint"], "notes": "Run pylint --fail-under=8.0"}
}
"""

import argparse
import json
import sys
from pathlib import Path
from datetime import datetime, timezone


SCORE_EMOJI = {"pass": "✅", "concern": "⚠️", "block": "❌"}


def load_input(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def generate(data: dict) -> str:
    files = data.get("files_reviewed", [])
    dimensions = data.get("dimensions", {})
    action_items = data.get("action_items", [])
    highlights = data.get("highlights", [])
    static = data.get("static_analysis", {})

    pass_count = sum(1 for d in dimensions.values() if d.get("score") == "pass")
    total_dims = len(dimensions)
    blockers = sum(1 for a in action_items if a.get("priority") == "Block")
    concerns = sum(1 for a in action_items if a.get("priority") == "Concern")
    suggestions = sum(1 for a in action_items if a.get("priority") == "Suggestion")

    lines = []
    lines.append("# NFR Code Review Report")
    lines.append("")
    lines.append(f"_Generated at {datetime.now(timezone.utc).isoformat()}_")
    lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Files Reviewed**: {len(files)}")
    if files:
        lines.append(f"- **Scope**: {', '.join(files)}")
    lines.append(f"- **Overall Score**: {pass_count}/{total_dims} dimensions passing")
    lines.append(f"- **Blockers**: {blockers} | **Concerns**: {concerns} | **Suggestions**: {suggestions}")
    lines.append("")

    # Dimension Scores
    lines.append("## Dimension Scores")
    lines.append("")
    for dim_name in ("Code Design", "Readability", "Reliability", "Performance"):
        dim = dimensions.get(dim_name, {"score": "pass", "evidence": []})
        score = dim.get("score", "pass")
        emoji = SCORE_EMOJI.get(score, "⚪")
        lines.append(f"### {dim_name} — {emoji}")
        for ev in dim.get("evidence", []):
            lines.append(f"- {ev}")
        if not dim.get("evidence"):
            lines.append("- No issues noted.")
        lines.append("")

    # Static Analysis
    lines.append("## Static Analysis Recommendations")
    lines.append("")
    tools = static.get("tools", [])
    if tools:
        lines.append(f"- **Recommended Tools**: {', '.join(tools)}")
    notes = static.get("notes", "")
    if notes:
        lines.append(f"- **Notes**: {notes}")
    if not tools and not notes:
        lines.append("- No static analysis configured. Consider adding SonarQube or Semgrep to CI.")
    lines.append("")

    # Action Items
    lines.append("## Action Items")
    lines.append("")
    if action_items:
        lines.append("| Priority | Item | Location | Dimension |")
        lines.append("|----------|------|----------|-----------|")
        for item in action_items:
            prio = item.get("priority", "Suggestion")
            text = item.get("item", "").replace("|", "\\|")
            loc = item.get("location", "—")
            dim = item.get("dimension", "—")
            lines.append(f"| {prio} | {text} | {loc} | {dim} |")
    else:
        lines.append("No action items. Great work!")
    lines.append("")

    # Highlights
    lines.append("## Positive Highlights")
    lines.append("")
    if highlights:
        for h in highlights:
            lines.append(f"- 🌟 {h}")
    else:
        lines.append("- No specific highlights recorded.")
    lines.append("")

    lines.append("---")
    lines.append("_Report generated by nfr-code-review skill_")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate NFR review report")
    parser.add_argument("--input", "-i", required=True, help="Path to JSON input")
    parser.add_argument("--output", "-o", default="-", help="Path to output markdown (default: stdout)")
    args = parser.parse_args()

    if not Path(args.input).exists():
        print(f"Error: Input not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    data = load_input(args.input)
    report = generate(data)

    if args.output == "-":
        print(report)
    else:
        Path(args.output).write_text(report, encoding="utf-8")
        print(f"Report written to {args.output}")


if __name__ == "__main__":
    main()
